<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="795" started-at="2019-01-28T05:32:41Z" finished-at="2019-01-28T05:32:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="795" started-at="2019-01-28T05:32:41Z" finished-at="2019-01-28T05:32:41Z">
      <class name="com.task.TestTask1">
        <test-method status="PASS" signature="Launch_Browser()[pri:0, instance:com.task.TestTask1@1375618]" name="Launch_Browser" is-config="true" duration-ms="13145" started-at="2019-01-28T00:32:27Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_Browser -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.task.TestTask1@1375618]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="Verify_home()[pri:0, instance:com.task.TestTask1@1375618]" name="Verify_home" duration-ms="720" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_home -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.task.TestTask1@1375618]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="Verifyaboutsir()[pri:0, instance:com.task.TestTask1@1375618]" name="Verifyaboutsir" duration-ms="60" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [About Sir] but found [About Sir]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [About Sir] but found [About Sir]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.task.TestTask1.Verifyaboutsir(TestTask1.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verifyaboutsir -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.task.TestTask1@1375618]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.task.TestTask1@1375618]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="Close_Browser()[pri:0, instance:com.task.TestTask1@1375618]" name="Close_Browser" is-config="true" duration-ms="10" started-at="2019-01-28T00:32:41Z" finished-at="2019-01-28T00:32:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close_Browser -->
      </class> <!-- com.task.TestTask1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
